name       : kmail-account-wizard
version    : 17.08.2
release    : 1
source     :
    - https://download.kde.org/stable/applications/17.08.2/src/kmail-account-wizard-17.08.2.tar.xz : a7b9c3cab8cbebfaf0bc5541b5ab81a34499d947f81052bb3ad4bb8bc245c7e1
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : programming
summary    : KMail Account Wizard
description: |
    An application which assists you with the configuration of accounts in KMail.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5UiTools)
    - akonadi-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - kcmutils-devel
    - kcodecs-devel
    - kconfig-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kitemmodels-devel
    - kldap-devel
    - kmailtransport-devel
    - kmime-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kpimtextedit-devel
    - kross-devel
    - kservice-devel
    - ktexteditor-devel
    - kwallet-devel
    - kxmlgui-devel
    - libassuan-devel
    - libboost-devel
    - libkdepim-devel
    - libkleo-devel
    - openldap-devel
    - pimcommon-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
