name       : kmail-account-wizard
version    : 19.04.1
release    : 20
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.1/src/kmail-account-wizard-19.04.1.tar.xz : c6714c425daa3d79dfb47b5d18cff26b10b1b087e4472f627738494f06d04ab8
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming
summary    : KMail Account Wizard
description: |
    An application which assists you with the configuration of accounts in KMail.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5UiTools)
    - akonadi-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - kcmutils-devel
    - kcodecs-devel
    - kconfig-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kitemmodels-devel
    - kldap-devel
    - kmailtransport-devel
    - kmime-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kpimtextedit-devel
    - kross-devel
    - kservice-devel
    - ktexteditor-devel
    - kwallet-devel
    - kxmlgui-devel
    - libassuan-devel
    - libboost-devel
    - libkdepim-devel
    - libkleo-devel
    - openldap-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
