name       : kmail-account-wizard
version    : 20.04.0
release    : 34
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.0/src/kmail-account-wizard-20.04.0.tar.xz : cd4e1de469d403a85a26932504437bbb65944ac226c292d5fa7199febbc1ea4c
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming
summary    : KMail Account Wizard
description: |
    An application which assists you with the configuration of accounts in KMail.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5UiTools)
    - akonadi-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - kcmutils-devel
    - kcodecs-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kitemmodels-devel
    - kldap-devel
    - kmailtransport-devel
    - kmime-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kpimtextedit-devel
    - kross-devel
    - ktexteditor-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libboost-devel
    - libkdepim-devel
    - libkleo-devel
    - openldap-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
