name       : kmail-account-wizard
version    : 22.08.3
release    : 63
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/kmail-account-wizard-22.08.3.tar.xz : 27e5d92a7a7a7410e5cd3c658084dcc66a3469e966d2c795cff1a1893361c023
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming
summary    : KMail Account Wizard
description: |
    An application which assists you with the configuration of accounts in KMail.
builddeps  :
    - akonadi-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - gpgme-qt-devel
    - kcmutils-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kldap-devel
    - kmailtransport-devel
    - kmime-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kpimtextedit-devel
    - kross-devel
    - ktexteditor-devel
    - kwallet-devel
    - libkdepim-devel
    - libkleo-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
