name       : kmail-account-wizard
version    : 18.12.3
release    : 17
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.3/src/kmail-account-wizard-18.12.3.tar.xz : 102a4170cb4f80c7a9ba3aec7a4d34a3e6a8ca18c975b5c0ea33cf7bac9e21df
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming
summary    : KMail Account Wizard
description: |
    An application which assists you with the configuration of accounts in KMail.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5UiTools)
    - akonadi-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - kcmutils-devel
    - kcodecs-devel
    - kconfig-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kitemmodels-devel
    - kldap-devel
    - kmailtransport-devel
    - kmime-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kpimtextedit-devel
    - kross-devel
    - kservice-devel
    - ktexteditor-devel
    - kwallet-devel
    - kxmlgui-devel
    - libassuan-devel
    - libboost-devel
    - libkdepim-devel
    - libkleo-devel
    - openldap-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
